version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=pass
    volumes:
      - mongo_data_host:/data/db/
      - mongo_log_host:/var/log/mongodb/
      - mongo_initdb_scripts_host:/docker-entrypoint-initdb.d/
    command: [ "--bind_ip", "0.0.0.0" ]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: $APP_NAME
    #    container_name: $APP_NAME
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pass
      - SPRING_DATA_MONGODB_DATABASE=mongo


volumes:
  mongo_data_host:
  mongo_log_host:
  mongo_initdb_scripts_host:
