version: '3.8'

services:
  #service 1: definition of mongo database
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"


  #service 2: definition of spring-boot app
  product-service:
    image: product-service
    container_name: product-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
