version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=user_db
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
